version: '3'
services:
  web:
    build: ./web
    image: tv-web:latest
    volumes:
      - tv-streams:/tmp/stream
      - tv-web-media:/django/media
    hostname: tv-web
    networks:
      - tv
  nginx:
    build: ./nginx
    image: tv-nginx:latest
    ports:
      - "30000:80"
    volumes:
      - tv-streams:/tmp/stream
      - tv-web-media:/tmp/media
    hostname: tv-nginx
    networks:
      - tv
volumes:
  tv-web-media:
  tv-streams:
