# Generated by Django 2.1.5 on 2019-05-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
