# Generated by Django 2.1.5 on 2019-05-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20190502_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/player/media/logos/'),
        ),
    ]
