# Generated by Django 2.1.5 on 2019-05-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0003_stream_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stream',
            new_name='Channel',
        ),
    ]
