# Generated by Django 2.1.5 on 2019-05-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0011_auto_20190502_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='source_type',
            field=models.CharField(choices=[('Generic', 'Generic'), ('YouTube', 'YouTube')], default='Generic', max_length=128),
        ),
    ]
