# Generated by Django 2.2.1 on 2019-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0017_auto_20190516_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
