# Generated by Django 2.2.1 on 2019-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0020_auto_20190516_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='container_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
