# Generated by Django 2.2.3 on 2019-09-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0021_channel_container_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='container_id',
        ),
    ]
